version: 0.1.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    msbuild NuklearSharp\NuklearSharp.csproj /p:Configuration=Release /t:rebuild

    nuget restore NuklearSharp\NuklearSharp.NETStandard.csproj

    dotnet publish NuklearSharp\NuklearSharp.NETStandard.csproj /p:Configuration=Release

    nuget pack NuklearSharp\NuklearSharp.nuspec -Version %APPVEYOR_BUILD_VERSION%

    copy_zip_package_files.bat
    
    rename "ZipPackage" "NuklearSharp.%APPVEYOR_BUILD_VERSION%"
    
    7z a NuklearSharp.%APPVEYOR_BUILD_VERSION%.zip NuklearSharp.%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: NuklearSharp.$(appveyor_build_version).nupkg
    name: NuklearSharp.nupkg

  - path: NuklearSharp.$(appveyor_build_version).zip
    name: ZipPackage
deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: $(appveyor_build_version)
    auth_token:
      secure: nIpZ5N6iQIXVV8/kK/Y6BqY4KYD+y7HYdq+vTKv+LqZBbxHE9BuEgZAHGVDvmJKh
    artifact: ZipPackage
    draft: false
    prerelease: false

  - provider: NuGet
    api_key:
      secure: o02Abc+1Pg/C7FVPnbCA9i4RIakmOUcKjMBBCHDCbEhS69b+N05mV0xBe0ne2/Y4
    artifact: /.*\.nupkg/